### ISSUE TITLE
MalformedInputException when copying file

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Logging-Level-Evolution-Plugin#176]
```
!ENTRY edu.cuny.hunter.log.evaluation 4 0 2019-04-09 01:24:13.792
!MESSAGE Encountered exception during evaluation
!STACK 0
java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
        at java.io.BufferedReader$1.hasNext(BufferedReader.java:574)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
        at java.util.stream.LongPipeline.sum(LongPipeline.java:396)
        at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
        at edu.cuny.hunter.mylyngit.core.analysis.GitHistoryAnalyzer.copyToFile(GitHistoryAnalyzer.java:706)
        at edu.cuny.hunter.mylyngit.core.analysis.GitHistoryAnalyzer.copyHistoricalFile(GitHistoryAnalyzer.java:687)
        at edu.cuny.hunter.mylyngit.core.analysis.GitHistoryAnalyzer.modifyFile(GitHistoryAnalyzer.java:450)
        at edu.cuny.hunter.mylyngit.core.analysis.GitHistoryAnalyzer.processNonRenamingFiles(GitHistoryAnalyzer.java:296)
        at edu.cuny.hunter.mylyngit.core.analysis.GitHistoryAnalyzer.processOneCommit(GitHistoryAnalyzer.java:268)
        at edu.cuny.hunter.mylyngit.core.analysis.GitHistoryAnalyzer.<init>(GitHistoryAnalyzer.java:139)
        at edu.cuny.hunter.mylyngit.core.analysis.MylynGitPredictionProvider.bumpDOIValuesForAllGitMethods(MylynGitPredictionProvider.java:125)
        at edu.cuny.hunter.mylyngit.core.analysis.MylynGitPredictionProvider.processOneProject(MylynGitPredictionProvider.java:94)
        at edu.cuny.hunter.log.core.refactorings.LogRejuvenatingProcessor.processGitHistory(LogRejuvenatingProcessor.java:291)
        at edu.cuny.hunter.log.core.refactorings.LogRejuvenatingProcessor.checkFinalConditions(LogRejuvenatingProcessor.java:239)
        at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:225)
        at org.eclipse.ltk.core.refactoring.Refactoring.checkAllConditions(Refactoring.java:165)
        at edu.cuny.hunter.log.evaluation.handlers.EvaluationHandler.lambda$0(EvaluationHandler.java:138)
        at org.eclipse.core.runtime.jobs.Job$1.run(Job.java:164)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at java.io.BufferedReader$1.hasNext(BufferedReader.java:571)
        ... 24 more
```

**Comment by khatchad** [comment]
Found with N=1000.

**Comment by khatchad** [comment]
It also seems that some files are in the CWD as well.

**Comment by khatchad** [comment]
That may give us some clues.

**Comment by khatchad** [comment]
There's a directory called "tmp_A_469" that has a file called FindbugsTestPlugin.java.

**Comment by khatchad** [comment]
I found this in the spotbugs directory: `./eclipsePlugin-test/src/de/tobject/findbugs/FindbugsTestPlugin.java`

**Comment by khatchad** [comment]
So, it looks like this happens with the spotbugs project using N=1000.

**Comment by khatchad** [comment]
I can repro it with running the evaluator on the `eclipsePlugin-test` subproject of spotbugs with N=1000.

**Comment by khatchad** [comment]
Some file came out too.

**Comment by khatchad** [comment]
Looks like it's a unicode character in the file.
